lead_strategist_task:
  description: >
      Review and integrate all agent outputs (diagnostics, education paths, talent matching, AI business use cases, and impact projections).
       Develop a comprehensive policy proposal or scalable pilot program.
  expected_output: >
        Strategic document including: goals, phases, KPIs, responsible actors, timeline and budget.
        Pitch deck or executive summary for stakeholders.
  agent: lead_strategist

tech_diag_task:
  description: >
    Research job portals, government reports and education statistics to identify the top 3 tech roles currently in demand in Colombia. 
    Analyze the required technical and soft skills for each role.
    Compare these with current educational offerings to identify gaps.
  expected_output: >
    List or table with the top 3 most in-demand tech roles.
    Comparative table of technical and soft skills required per profile.
    Gap analysis between current training offerings and market needs.
  agent: tech_talent_diagnostics_agent

education_agent_task:
  description: >
    Based on the roles and skill gaps provided by the diagnostics agent, design adaptive learning pathways using accessible online resources. 
    Tailor the content to the Colombian context.
  expected_output: >
      Learning paths (one per profile) with suggested modules.
      Table showing estimated duration per module and difficulty level.
      Links to recommended platforms or content.
  agent: education_content_curation_agent

connector_task:
  description: >
      Identify tech companies, startups, and hiring platforms interested in the identified roles. 
      Design a mechanism to match trained individuals with job opportunities.
  expected_output: >
        Talent connection strategy (manual or automated matching).
        Table with suggested platforms and potential employer partners.
        Examples of real job openings related to the prioritized profiles.
  agent: talent_opportunity_connector_agent

ai_advisor_task:
  description: >
      Evaluate AI readiness in Colombian SMEs. Identify business processes suitable for AI (e.g., customer service, sales analytics). 
      Recommend user-friendly tools for implementation.
  expected_output: >
        Realistic automation proposals for Colombian SMEs.
        Table of accessible tools for each use case (e.g., ChatGPT, Zapier).
        Step-by-step implementation guides for each use case.
  agent: ai_advisor_for_companies_agent

impact_agent_task:
  description: >
        Using outputs from all other agents, define KPIs and forecast potential impacts (jobs created, productivity increase, upskilled individuals, etc.).
        Benchmark with similar initiatives globally.
  expected_output: >
        Impact report including: metrics, projections, scalability analysis.
        ROI estimation and long-term benefits.
  agent: impact_evaluator_agent